### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Estayparadox** [OceanShare/OceanShare-iOS#35]
make a new logo
change the colour
change the position of the logo on the login view and the signup view

**Comment by Estayparadox** [comment]
Hi @richardbmx !

First, thank you for paying attention to our project.
We would be happy to receive new logo ideas from you.

We must create a Logo for our application related to the world of yachting. For now, our logo is the one on the screenshots below. We particularly like the idea of ​​the ship steering wheel we would like to keep.

<img width="205" alt="capture d ecran 2019-01-26 a 10 54 34" src="https://user-images.githubusercontent.com/19834789/51781855-c73d4c80-2159-11e9-9895-4e1099b40aa1.png">

If you want to share your creations, you can contact us at this address: joseph.pereniguez@epitech.eu

The OceanShare team, boaters and developers. ⛵️

**Comment by richardbmx** [comment]
@Estayparadox  Here you can find a Google folder with all the necessary files to use the logo, find different variations in different formats and also open a file that grants all the rights for free use. I have also created a PR by adding the Logo to the project and in the Readme file [Pull](https://github.com/OceanShare/OceanShare-iOS/pull/41)

[Google Drive](https://drive.google.com/open?id=1-dMcYE3PLxjqEiZx67RPae_fuGya-orn)

**Comment by Estayparadox** [comment]
@richardbmx Thanks again !

Feel free to contribute again in our project.

The OceanShare team, boaters and developers. ⛵️
